name: cats_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.7.2
  provider: ^6.1.2
  dio: ^5.8.0+1
  equatable: ^2.0.7
  get_it: ^8.0.3
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
