name: Build and Analyze

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get

      - run: flutter test --coverage

      - name: Set up SonarScanner
        uses: warchant/setup-sonar-scanner@v7

      - name: Run SonarCloud Scan
        run: sonar-scanner
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.organization=demanzanoc
          -Dsonar.projectKey=demanzanoc_cat_breeds
          -Dsonar.sources=lib
          -Dsonar.tests=test
          -Dsonar.dart.coverage.reportPath=coverage/lcov.info
